{"uuid": "89221a02-8cff-474b-9790-4be554328da3", "children": ["d905cbd7-48f4-4d54-b889-24ad7d3576de", "ff77df2f-48f7-43a0-b21a-4dba1ea1220d", "a80cc496-37d1-42e8-a54f-ab570c6a2743", "4b688676-144a-4950-a8d4-f4a1258348e4", "5758e207-d95a-483d-b3e0-813aaf220f7b"], "befores": [{"name": "cmd_option", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/data/add_data.yaml'\n", "trace": "  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\python3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\开发项目\\Caculator\\conftest.py\", line 83, in cmd_option\n    with open(data_path, \"r\", encoding=\"utf-8\") as f:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715221915113, "stop": 1715221915113}], "start": 1715221915113, "stop": 1715221915260}